=== synergy-design-system/synergy-design-system/packages/metadata/data/schemas/core-entity.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "custom": {
      "additionalProperties": {},
      "propertyNames": {
        "type": "string"
      },
      "type": "object"
    },
    "id": {
      "type": "string"
    },
    "kind": {
      "enum": [
        "asset",
        "component",
        "style",
        "setup",
        "template",
        "token",
        "utility"
      ],
      "type": "string"
    },
    "layers": {
      "additionalProperties": {
        "items": {
          "additionalProperties": false,
          "properties": {
            "layer": {
              "enum": [
                "examples",
                "interface",
                "rules",
                "full"
              ],
              "type": "string"
            },
            "path": {
              "type": "string"
            }
          },
          "required": [
            "layer",
            "path"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "default": {},
      "propertyNames": {
        "type": "string"
      },
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "package": {
      "type": "string"
    },
    "relations": {
      "default": [],
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "enum": [
              "dependsOn",
              "usedBy",
              "partOf",
              "relates"
            ],
            "type": "string"
          }
        },
        "required": [
          "id",
          "type"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "since": {
      "type": "string"
    },
    "sources": {
      "default": [],
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "status": {
      "enum": [
        "stable",
        "beta",
        "experimental",
        "deprecated"
      ],
      "type": "string"
    },
    "tags": {
      "default": [],
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "id",
    "kind",
    "layers",
    "name",
    "package",
    "relations",
    "since",
    "sources",
    "status",
    "tags"
  ],
  "type": "object"
}

=== synergy-design-system/synergy-design-system/packages/metadata/data/core/component/component:syn-textarea.json
{
  "custom": {
    "clusters": [
      "components-by-tag/form"
    ],
    "frameworks": {
      "angular": {
        "componentName": "SynTextareaComponent",
        "exportPath": "packages/angular/index.ts",
        "packageName": "@synergy-design-system/angular",
        "selector": "syn-textarea",
        "sourcePath": "packages/angular/components/textarea/textarea.component.ts"
      },
      "react": {
        "jsx": {
          "componentName": "SynTextarea",
          "documentation": "https://synergy-design-system.github.io/?path=/docs/components-syn-textarea--docs",
          "events": [
            {
              "name": "syn-blur",
              "type": "SynBlurEvent"
            },
            {
              "name": "syn-change",
              "type": "SynChangeEvent"
            },
            {
              "name": "syn-focus",
              "type": "SynFocusEvent"
            },
            {
              "name": "syn-input",
              "type": "SynInputEvent"
            },
            {
              "name": "syn-invalid",
              "type": "SynInvalidEvent"
            }
          ],
          "packageName": "@synergy-design-system/react",
          "since": "1.0.0",
          "sourcePath": "packages/react/src/types/syn-jsx-elements.ts",
          "status": "stable",
          "subpathExport": "./types/latest",
          "typeName": "SynTextareaJSXElement"
        },
        "wrapper": {
          "componentName": "SynTextarea",
          "exportPath": "packages/react/src/index.ts",
          "packageName": "@synergy-design-system/react",
          "sourcePath": "packages/react/src/components/textarea.ts"
        }
      },
      "vue": {
        "componentName": "SynVueTextarea",
        "exportPath": "packages/vue/src/index.ts",
        "packageName": "@synergy-design-system/vue",
        "sourcePath": "packages/vue/src/components/SynVueTextarea.vue"
      }
    },
    "override": {
      "figmaComponentId": "41337-204379",
      "stories": [
        {
          "description": {
            "type": "text",
            "value": "Textareas collect data from the user and allow multiple lines of text."
          },
          "name": "default",
          "title": {
            "type": "text",
            "value": "Textarea"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the label attribute to give the textarea an accessible label. For labels that contain HTML, use the label slot instead."
          },
          "name": "labels",
          "title": {
            "type": "text",
            "value": "Labels"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Add descriptive help text to a switch with the help-text attribute. For help texts that contain HTML, use the help-text slot instead.\nThe help-text attribute should not be used to display error messages. To handle validation and error messaging, use syn-validate for proper error management."
          },
          "name": "help-text",
          "title": {
            "type": "text",
            "value": "Help Text"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the rows attribute to change the number of text rows that get shown."
          },
          "name": "rows",
          "title": {
            "type": "text",
            "value": "Rows"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the placeholder attribute to add a placeholder."
          },
          "name": "placeholder",
          "title": {
            "type": "text",
            "value": "Placeholders"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Add the readonly attribute to draw a read-only textarea."
          },
          "name": "readonly",
          "title": {
            "type": "text",
            "value": "Read-only Textareas"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the disabled attribute to disable a textarea."
          },
          "name": "disabled",
          "title": {
            "type": "text",
            "value": "Disabled"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the size attribute to change a textarea’s size."
          },
          "name": "size",
          "title": {
            "type": "text",
            "value": "Sizes"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "By default, textareas can be resized vertically by the user. To prevent resizing, set the resize attribute to none."
          },
          "name": "resize",
          "title": {
            "type": "text",
            "value": "Prevent Resizing"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Textareas will automatically resize to expand to fit their content when resize is set to auto."
          },
          "name": "resize-auto",
          "title": {
            "type": "text",
            "value": "Expand with Content"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "The focus event gives the user feedback that the Textarea has been focused by the keyboard interaction and that the Textarea component is ready for use."
          },
          "name": "focus",
          "title": {
            "type": "text",
            "value": "Focus / Active"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "The invalid status is used to warn the user that the input is invalid. For example, if the entry of text is mandatory and nothing has been entered or if a text has been entered that does not have the correct format."
          },
          "name": "invalid",
          "title": {
            "type": "text",
            "value": "Invalid"
          }
        }
      ],
      "storySourcePath": "components.textarea",
      "storyTags": [
        "Form"
      ]
    },
    "sourceModulePath": "components/textarea/textarea.js",
    "summary": "Textareas collect data from the user and allow multiple lines of text."
  },
  "id": "component:syn-textarea",
  "kind": "component",
  "layers": {
    "examples": [
      {
        "layer": "examples",
        "path": "layers/examples/component/component:syn-textarea.md"
      }
    ],
    "full": [
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/angular/textarea.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/components/textarea.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/components/textarea.styles.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/components/textarea.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/react/textarea.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/vue/SynVueTextarea.vue"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-textarea/react/SynTextareaJSXElement.ts"
      }
    ],
    "interface": [
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-textarea.json"
      },
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-textarea.md"
      }
    ]
  },
  "name": "syn-textarea",
  "package": "components",
  "relations": [],
  "since": "1.0.0",
  "sources": [
    "packages/angular/components/textarea/textarea.component.ts",
    "packages/components/src/components/textarea/textarea.component.ts",
    "packages/components/src/components/textarea/textarea.styles.ts",
    "packages/components/src/components/textarea/textarea.ts",
    "packages/react/src/components/textarea.ts",
    "packages/vue/src/components/SynVueTextarea.vue"
  ],
  "status": "stable",
  "tags": [
    "angular",
    "component",
    "react",
    "syn-textarea",
    "textarea",
    "vue"
  ]
}

=== synergy-design-system/synergy-design-system/packages/metadata/data/core/component/component:syn-progress-bar.json
{
  "custom": {
    "clusters": [
      "components-by-tag/feedback"
    ],
    "frameworks": {
      "angular": {
        "componentName": "SynProgressBarComponent",
        "exportPath": "packages/angular/index.ts",
        "packageName": "@synergy-design-system/angular",
        "selector": "syn-progress-bar",
        "sourcePath": "packages/angular/components/progress-bar/progress-bar.component.ts"
      },
      "react": {
        "jsx": {
          "componentName": "SynProgressBar",
          "documentation": "https://synergy-design-system.github.io/?path=/docs/components-syn-progress-bar--docs",
          "events": [],
          "packageName": "@synergy-design-system/react",
          "since": "1.19.0",
          "sourcePath": "packages/react/src/types/syn-jsx-elements.ts",
          "status": "stable",
          "subpathExport": "./types/latest",
          "typeName": "SynProgressBarJSXElement"
        },
        "wrapper": {
          "componentName": "SynProgressBar",
          "exportPath": "packages/react/src/index.ts",
          "packageName": "@synergy-design-system/react",
          "sourcePath": "packages/react/src/components/progress-bar.ts"
        }
      },
      "vue": {
        "componentName": "SynVueProgressBar",
        "exportPath": "packages/vue/src/index.ts",
        "packageName": "@synergy-design-system/vue",
        "sourcePath": "packages/vue/src/components/SynVueProgressBar.vue"
      }
    },
    "override": {
      "figmaComponentId": "41203-297162",
      "stories": [
        {
          "description": {
            "type": "text",
            "value": "Progress bars are used to show the status of an ongoing operation."
          },
          "name": "default",
          "title": {
            "type": "text",
            "value": "Progress Bar"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the `label` attribute to label the progress bar and tell assistive devices how to announce it."
          },
          "name": "labels",
          "title": {
            "type": "text",
            "value": "Labels"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the --height custom property to set the progress bar’s height."
          },
          "name": "custom-height",
          "title": {
            "type": "text",
            "value": "Custom Height"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Use the default slot to show a value."
          },
          "name": "showing-values",
          "title": {
            "type": "text",
            "value": "Showing Values"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "The indeterminate attribute can be used to inform the user that the operation is pending, but its status cannot currently be determined. In this state, value is ignored and the label, if present, will not be shown."
          },
          "name": "indeterminate",
          "title": {
            "type": "text",
            "value": "Indeterminate"
          }
        }
      ],
      "storySourcePath": "components.progress-bar",
      "storyTags": [
        "Feedback"
      ]
    },
    "sourceModulePath": "components/progress-bar/progress-bar.js",
    "summary": "Progress bars are used to show the status of an ongoing operation."
  },
  "id": "component:syn-progress-bar",
  "kind": "component",
  "layers": {
    "examples": [
      {
        "layer": "examples",
        "path": "layers/examples/component/component:syn-progress-bar.md"
      }
    ],
    "full": [
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/angular/progress-bar.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/components/progress-bar.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/components/progress-bar.custom.styles.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/components/progress-bar.styles.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/components/progress-bar.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/react/progress-bar.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/vue/SynVueProgressBar.vue"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-progress-bar/react/SynProgressBarJSXElement.ts"
      }
    ],
    "interface": [
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-progress-bar.json"
      },
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-progress-bar.md"
      }
    ]
  },
  "name": "syn-progress-bar",
  "package": "components",
  "relations": [],
  "since": "1.19.0",
  "sources": [
    "packages/angular/components/progress-bar/progress-bar.component.ts",
    "packages/components/src/components/progress-bar/progress-bar.component.ts",
    "packages/components/src/components/progress-bar/progress-bar.custom.styles.ts",
    "packages/components/src/components/progress-bar/progress-bar.styles.ts",
    "packages/components/src/components/progress-bar/progress-bar.ts",
    "packages/react/src/components/progress-bar.ts",
    "packages/vue/src/components/SynVueProgressBar.vue"
  ],
  "status": "stable",
  "tags": [
    "angular",
    "component",
    "progress-bar",
    "react",
    "syn-progress-bar",
    "vue"
  ]
}

=== synergy-design-system/synergy-design-system/packages/metadata/data/core/component/component:syn-spinner.json
{
  "custom": {
    "clusters": [
      "components-by-tag/feedback"
    ],
    "frameworks": {
      "angular": {
        "componentName": "SynSpinnerComponent",
        "exportPath": "packages/angular/index.ts",
        "packageName": "@synergy-design-system/angular",
        "selector": "syn-spinner",
        "sourcePath": "packages/angular/components/spinner/spinner.component.ts"
      },
      "react": {
        "jsx": {
          "componentName": "SynSpinner",
          "documentation": "https://synergy-design-system.github.io/?path=/docs/components-syn-spinner--docs",
          "events": [],
          "packageName": "@synergy-design-system/react",
          "since": "1.22.0",
          "sourcePath": "packages/react/src/types/syn-jsx-elements.ts",
          "status": "stable",
          "subpathExport": "./types/latest",
          "typeName": "SynSpinnerJSXElement"
        },
        "wrapper": {
          "componentName": "SynSpinner",
          "exportPath": "packages/react/src/index.ts",
          "packageName": "@synergy-design-system/react",
          "sourcePath": "packages/react/src/components/spinner.ts"
        }
      },
      "vue": {
        "componentName": "SynVueSpinner",
        "exportPath": "packages/vue/src/index.ts",
        "packageName": "@synergy-design-system/vue",
        "sourcePath": "packages/vue/src/components/SynVueSpinner.vue"
      }
    },
    "override": {
      "figmaComponentId": "17016-71772",
      "figmaDocsId": "41227-223775",
      "stories": [
        {
          "description": {
            "type": "text",
            "value": "Spinners are used to show the progress of an indeterminate operation."
          },
          "name": "default",
          "title": {
            "type": "text",
            "value": "Spinner"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "Spinners are sized based on the current font size. To change their size, set the font-size property on the spinner itself or on a parent element as shown below."
          },
          "name": "size",
          "title": {
            "type": "text",
            "value": "Size"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "The width of the spinner’s track can be changed by setting the --track-width custom property."
          },
          "name": "track-width",
          "title": {
            "type": "text",
            "value": "Track Width"
          }
        },
        {
          "description": {
            "type": "text",
            "value": "The spinner’s colors can be changed by setting the --indicator-color and --track-color custom properties."
          },
          "name": "color",
          "title": {
            "type": "text",
            "value": "Color"
          }
        }
      ],
      "storySourcePath": "components.spinner",
      "storyTags": [
        "Feedback"
      ]
    },
    "rules": {
      "accessibility": [
        "Assign role=\"status\" or use a live region (e.g., aria-live=\"polite\") to inform screen reader users of ongoing loading.",
        "A spinner shouldn't itself be focusable or interactive, nor prevent from navigating to other parts of the page while loading continues."
      ],
      "component": "syn-spinner",
      "knownIssues": [
        {
          "browser": "Safari",
          "description": "The spinner component may experience animation issues in Safari, causing it to appear wobbly."
        }
      ],
      "usageGuidelines": [
        {
          "content": [
            "Use for processes that take a short amount of time (typically under 4 seconds).",
            "Apply within specific sections rather than blocking the entire page, unless absolutely necessary.",
            "Place in a consistent location relative to the content it is loading."
          ],
          "id": "behavior_and_placement",
          "name": "Behavior and Placement"
        },
        {
          "content": [
            "Include a label or message to provide context about what is being loaded, especially if the loading time is long."
          ],
          "id": "content",
          "name": "Content"
        },
        {
          "content": [
            "Maintain consistency in size and style; avoid using spinners of varying sizes on the same page."
          ],
          "id": "styling",
          "name": "Styling"
        }
      ],
      "useCases": [
        "Indicate that content is being loaded, such as when fetching data from a server or loading a new page.",
        "Show ongoing background processes, like file uploads or data processing tasks.",
        "Used within buttons or interactive elements to indicate that an action is being processed.",
        "Apply to sections of a page that are loading independently, such as widgets or panels.",
        "Display when a form is being submitted to show that the submission is in progress."
      ]
    },
    "sourceModulePath": "components/spinner/spinner.js",
    "summary": "Spinners are used to show the progress of an indeterminate operation."
  },
  "id": "component:syn-spinner",
  "kind": "component",
  "layers": {
    "examples": [
      {
        "layer": "examples",
        "path": "layers/examples/component/component:syn-spinner.md"
      }
    ],
    "full": [
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/angular/spinner.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/components/spinner.component.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/components/spinner.custom.styles.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/components/spinner.styles.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/components/spinner.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/react/spinner.ts"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/vue/SynVueSpinner.vue"
      },
      {
        "layer": "full",
        "path": "layers/full/component/component:syn-spinner/react/SynSpinnerJSXElement.ts"
      }
    ],
    "interface": [
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-spinner.json"
      },
      {
        "layer": "interface",
        "path": "layers/interface/component/component:syn-spinner.md"
      }
    ],
    "rules": [
      {
        "layer": "rules",
        "path": "layers/rules/component/component:syn-spinner.md"
      }
    ]
  },
  "name": "syn-spinner",
  "package": "components",
  "relations": [],
  "since": "1.22.0",
  "sources": [
    "packages/angular/components/spinner/spinner.component.ts",
    "packages/components/src/components/spinner/spinner.component.ts",
    "packages/components/src/components/spinner/spinner.custom.styles.ts",
    "packages/components/src/components/spinner/spinner.styles.ts",
    "packages/components/src/components/spinner/spinner.ts",
    "packages/react/src/components/spinner.ts",
    "packages/vue/src/components/SynVueSpinner.vue"
  ],
  "status": "stable",
  "tags": [
    "angular",
    "component",
    "react",
    "spinner",
    "syn-spinner",
    "vue"
  ]
}
